#!/bin/bash

set -e
set -o pipefail

APP=$(grep defproject project.clj | awk '{print $2}')

if [[ -n "${WILDFLY_PORT_9990_TCP_ADDR}" ]]; then
  if [[ -z "${WILDFLY_ENV_ADMIN_USERNAME}" || -z "${WILDFLY_ENV_ADMIN_PASSWORD}" ]]; then
    echo "WILDFLY_ENV_ADMIN_USERNAME and WILDFLY_ENV_ADMIN_PASSWORD must be set"
    exit 1
  fi
fi

WILDFLY_ADMIN_URL="http://${WILDFLY_ENV_ADMIN_USERNAME}:${WILDFLY_ENV_ADMIN_PASSWORD}@${WILDFLY_PORT_9990_TCP_ADDR}:${WILDFLY_PORT_9990_TCP_PORT}/management"

DEPLOYED=no

function wildfly_operation {
  local json=${1}
  local response=$(curl -s -S -H "Content-Type: application/json" -d "${json}" --digest ${WILDFLY_ADMIN_URL} | awk '{printf("%s",$0);}')
  if [[ $(echo "${response}" | jq -c -r '.outcome') != "success" ]]; then
    deploy_failure "${APP} error from WildFly: ${response}\n\nPayload: ${json}"
    return 1
  fi
  echo "${response}"
  return 0
}

function ensure_war {
  if [[ ! -e target/${APP}.war ]]; then
    echo "NOTICE: No ${APP}.war file found in /target dir. Building it now..."
    lein immutant war --name ${APP} --destination target
  fi
}

function configure_war {
  # render env vars into the config file before we build the WAR file
  local cwd=$(pwd)
  local tmpdir=${cwd}/target/tmp
  mkdir -p $tmpdir
  cd /opt/didor && bundle exec ./read_edn.rb ${cwd}/resources/config.edn > ${tmpdir}/config.edn
  echo "WAR config: $(<${tmpdir}/config.edn)"
  cd ${tmpdir}
  jar -xf ../${APP}.war WEB-INF/lib/${APP}.jar
  jar -uf WEB-INF/lib/${APP}.jar -C ${tmpdir} config.edn
  jar -uf ../${APP}.war WEB-INF/lib/${APP}.jar
  cd ${cwd}
  rm -rf ${tmpdir}
}

function undeploy {
  if [[ "${DEPLOYED}" == "yes" ]]; then
    echo "Undeploying ${APP}... "
    IGNORE=$(wildfly_operation "{\"operation\": \"undeploy\", \"address\": [{\"deployment\": \"${APP}.war\"}]}")
    IGNORE=$(wildfly_operation "{\"operation\": \"remove\", \"address\": [{\"deployment\": \"${APP}.war\"}]}")
    echo "Done."
  fi
}

function deploy_failure {
  echo "Deploy failed: ${1}"
  exit 1
}

function wait_for_wildfly {
  echo "Waiting for WildFly at ${WILDFLY_PORT_9990_TCP_ADDR} ${WILDFLY_PORT_9990_TCP_PORT} ... "
  for i in {1..30}; do
    if curl -sf --digest $WILDFLY_ADMIN_URL | jq '.' >/dev/null 2>&1; then
      echo "Wildfly is there!"
      return 0
    fi
    echo "WildFly not found, waiting..."
    sleep $i
  done
  deploy_failure "Could not find Wildfly at ${WILDFLY_PORT_9990_TCP_ADDR} ${WILDFLY_PORT_9990_TCP_PORT}"
  return 1
}

trap undeploy EXIT

if [[ -n "${NO_LEIN_RUN}" || -n "${WILDFLY_PORT_9990_TCP_ADDR}" ]]; then
  ensure_war
  echo "Configuring ${APP} WAR file..."
  configure_war

  wait_for_wildfly

  echo "Deploying ${APP} to WildFly... "
  WILDFLY_RESPONSE=$(curl -s -S -F "file=@target/${APP}.war" --digest ${WILDFLY_ADMIN_URL}/add-content)
  WILDFLY_CONTENT=$(echo "${WILDFLY_RESPONSE}" | jq -c 'if .outcome == "success" then .result else "error" end')
  if [[ "${WILDFLY_CONTENT}" != "error" ]]; then
    DEPLOYED=yes
    wildfly_operation "{\"content\":[{\"hash\": ${WILDFLY_CONTENT}}], \"address\": [{\"deployment\": \"${APP}.war\"}], \"operation\": \"add\", \"enabled\": \"true\"}"
  else
    deploy_failure "${WILDFLY_RESPONSE}"
  fi
  echo "Done."
  sleep infinity
else
  echo "No WildFly container found, using lein run"
  exec lein run
fi
